### ISSUE TITLE
Does the current version v0.5.2 support kotlinx-serialization 1.0.0?

### ISSUE THREAD

**Issue by vngantk** [Ricky12Awesome/json-schema-serialization#2]

**Comment by NiematojakTomasz** [comment]
Seems it doesn't

**Comment by Ricky12Awesome** [comment]
Not yet, been busy doing other stuff but I am planning on updating it and also re-working a few things.

**Comment by NiematojakTomasz** [comment]
@Ricky12Awesome See PR I made today - https://github.com/Ricky12Awesome/json-schema-serialization/pull/3 : )

**Comment by Ricky12Awesome** [comment]
v0.6.0 now supports kotlinx.serialization 1.0.1, also changes to few names to more like it as well. (like `stringifyToSchema` is now `encodeToSchema`)
